[global]
keyboard = "en-us"
country = "vn"
fqdn = "pve-master.local"
mailto = "ngovuminhdat@gmail.com"
timezone = "Asia/Ho_Chi_Minh"
root-password-hashed = "$y$j9T$RRqA6BV/Zs7n6rEjgMcwY/$mFY517PsCgu.IaKQG3sc3G/Z0eFq.flca5c6I5OeV7B"
root-ssh-keys = [
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCm6CxC3POGQJQfRRo5GBeKnAOG+lg9+CGupZYv7DXTZFTq9/kWiA60KfDvqIy81K8jv74lnrF9kBJpy/MnSqU6VupgatpGxvmiXxU9wr/35kPCd/8XI+v8a+pOtvmHcQK6M65oOW8Pzs1jkbcdFxHGmjRng87Q6Fq6+GOr1EU7IGCQccPN0Tw555+OzfMmKoIoO0Sf1ky3tWATXvuqJXZmB/h31OOhpR3mgnSg2qtfsjHBVFexsyq8HCfIyD6Ne0eWGCh9p2pRTnj9+eqkAsYF/oVqNJS8bR8ASqvAHewBK0kYgG2AL5TKQAZfPJ1vu2SuiHCBEew/VHFYYsC+7Ilx61/ZL6m8kd8iObv/iXTjzy/g9mgff9bFyPQx9dMt9H0rSABO8zPQLcDADvadSlxPo7v2fh8AhOIUh8ZYNPjNydyM49aQNFj8URM2QDhcncNtoZ3UsUYlL1VCqYZgyKtP9fTF8Y8p2B+DCtPo5yak5ITWAyiPBPck7z1f8tw9mKE= ngovu@LAPTOP-9NBAONU6"
]


[network]
# No dependency on DHCP — just set loopback + placeholder bridge
source = "from-dhcp"

[disk-setup]
filesystem = "ext4"
disk-list = ["sda"]


[first-boot]
source = "from-iso"
ordering = "before-network"
